### PR TITLE
Addressing issue #110 plus other fixes on new_experiment() and make_wkdir()

### PR DESCRIPTION
**Pull request by choisy**
* Adding an `output` slot to the structure of `experiment`
* Adding tests to `new_experiment()`
* Adding comments and cleaning `new_experiment()`
* Adding a message to `make_wkdir()`
* Fixing minor bugs in the tests of `new_experiment()`

### CODE REVIEW

**Comment by LucieContamin** [comment]
The current version of the object `experiment` (with a new column `output` containing `NA`) returns an error when inputted in `run_experiment()` because, currently, the function uses `is.experiment()` to test to object before any other action and `is.experiment` return an error if the object contains `NA` as it seems to be problematic with GAMA.
So, I propose to re-write the function `is.experiment` to test only if the columns `parameters`, `obs_rates`, `seed` and `tmax` do not contain `NA`. 
Furthermore, the column `output` does not appear with the function `print.experiment`. It should be update too.

**Comment by choisy** [comment]
"I propose to re-write": should I understand that you do it?
For `print.experiment()`, it can be done later in another branch.

**Comment by choisy** [comment]
Don't have have time to do it right now. We can do it later in another branch and another pull request.

**Comment by LucieContamin** [comment]
As the column `output` is not used currently, I agree to update `print.experiment` later

**Pull request merged**
