### PR TITLE
Addressing issue #62

### PR DESCRIPTION
**Pull request by choisy**
This branch addresses Jean-Daniel's issue #62. Please review and pull if good enough.
I'm not sure whether `tibble` should be in the `Imports` or in the `Depends`. In `dplyr` and `broom`, it's in `Imports`, so I've put it in `Imports` too. Let me know what you think.
I'm assigning the pull request to Lucie, Hai and Jean-Daniel. In terms of coordination, I guess it would be good that the one that decide to review the pull request informs the others by a message, just to make sure that you're not doing the same thing at the same time...

### CODE REVIEW

**Comment by LucieContamin** [comment]
I notice a problem with this new version of the object `experiment`. 

For example, if we create an object `experiment`: 

```r
df <-   data.frame(S0 = c(900, 800, 500), I0 = c(100, 200, 500), R0 = 0, beta = 1.5, gamma = .15, S = 
                                c(1,2,3),  I = c(2,4,6), R =c(10,20,30), nbiter = 1000, seed = "123456789")

exp0 <- experiment( df, parameters = c("S0","I0","R0","beta","gamma"), obsrates  = c("S", "I", "R"), 
                                    tmax = "nbiter", seed = "seed", experiment = "sir", 
                                    model = system.file("examples", "sir.gaml", package = "rama"), dir = "testsir")
class(exp0)
# [1] "experiment" "tbl_df"     "tbl"        "data.frame"
```
`exp0` is an object of class: `"experiment", "tbl_df", "tbl", "data.frame"`.

The problem is, if we use to select one row or one column by using `[`, we are losing the `experiment` class.
For example:
```r
 class(exp0[1,])
# [1] "tbl_df"     "tbl"        "data.frame"
```
It cause trouble with the function `save_to_gama` which used the line:
```r
row_id <- 1
 y <- parameters(exp0[row_id, ])
for (col_id in 1:ncol(y)) { 
    ...
}
# Error in 1:ncol(y) : argument of length 0
```
It returns an error because the function `parameters` can not be apply on exp0[1, ] because we lost the class `experiment`: 
```r
> parameters(exp0[1,])
[1] "Unknown class"
```

**Comment by choisy** [comment]
Very interesting! I'm on it!
Marc.

**Comment by choisy** [comment]
I think we need to redefine a number of methods, basically making sure that the class is preserved. It seems that it's what they do in the `tibble` package: https://github.com/tidyverse/tibble/blob/master/R/subsetting.R. Do you agree?

**Comment by LucieContamin** [comment]
Yes, I was also reading on tibble class object and it seems that they have their own method of subsetting like you just send. https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html. So,  I agree with you, we should redefine `[`, `[[` method and check `print` and `$` method for the conservation of the `experiment` class.

**Comment by choisy** [comment]
Yes, and their key function making sure that the class is preserved seems to be `vec_restore_tbl_df_with_nr()` at the end of the https://github.com/tidyverse/tibble/blob/master/R/subsetting.R file. (it's called by all the other functions of this file, at the `return` calls). Do you agree?
So, we probably want to also have a `subsetting.R` file right? Agree?

**Comment by choisy** [comment]
It seems that our neat new constructor and validator for the class `experiment` solved the issues reported above. Furthermore, the few changes done in this branch have already been done by previous commits (already merged to master) on the definition of the constructor and validator of the class `experiment`. And since this branch is way behind master in terms of commits, I suggest that we abandon the branch, delete it and close the issue #62 that has been addressed by the constructor of the `experiment` class. Do you agree with that? If yes, I'll take care of these actions.

**Comment by LucieContamin** [comment]
I agree with closing this branch

**Comment by choisy** [comment]
OK, we thus decide to close the pull request without merging the branch and to delete it.

**Pull request closed without merging**
